server:
  port: 8080 # The standard port for an API Gateway

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173" # Allows your React App
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        # Route for the Zone Service
        - id: zone-service
          uri: lb://zone-service # Matches the spring.application.name of your zone service
          predicates:
            - Path=/zone-service/** # Matches what React is calling
          filters:
            - StripPrefix=1 # Removes "/zone-service" before sending to port 8081

        # Route for the Sensor Service
        - id: sensor-service
          uri: lb://telemetry-service
          predicates:
            - Path=/telemetry-service/**
          filters:
            - StripPrefix=1

        # Route for the Automation Service
        - id: automation-service
          uri: lb://automation-service
          predicates:
            - Path=/automation-service/**
          filters:
            - StripPrefix=1

        # Route for the Crop Inventory Service
        - id: crop-service
          uri: lb://crop-inventory-service
          predicates:
            - Path=/crop-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/